# Generated by Django 2.0.2 on 2018-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=255)),
                ('steps', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
